# Generated by Django 5.0 on 2023-12-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_archived',
            field=models.BooleanField(default=0),
        ),
    ]
