# Generated by Django 5.0 on 2023-12-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
