# Generated by Django 5.0 on 2023-12-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrdersApp', '0006_alter_purchaseorder_quality_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quality_rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
